---
# External Secret for Thanos object storage config
# This creates the objstore.yml config that Thanos sidecar uses to upload
# Prometheus data blocks to MinIO S3 for long-term storage
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: thanos-objstore-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        objstore.yml: |
          type: s3
          config:
            bucket: thanos
            endpoint: minio.minio.svc.cluster.local:9000
            access_key: {{ .rootUser }}
            secret_key: {{ .rootPassword }}
            insecure: true
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-credentials
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: minio-credentials
        property: password
