---
# External Secret for MinIO root credentials
# 1Password item: minio-credentials in vault "homeserver"
# Fields: root-user, root-password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-credentials
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: minio-credentials
        property: password
