---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mqtt-credentials
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: mqtt-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: zigbee2mqtt-mqtt
        property: username
    - secretKey: password
      remoteRef:
        key: zigbee2mqtt-mqtt
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgresql
        property: postgres-password
