---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: authelia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-authelia
roleRef:
  kind: ClusterRole
  name: external-secrets-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: authelia
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: local-secrets
  namespace: authelia
spec:
  provider:
    kubernetes:
      remoteNamespace: authelia
      auth:
        serviceAccount:
          name: external-secrets-sa
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-credentials
  namespace: authelia
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authelia-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: authelia-login
        property: username
    - secretKey: password
      remoteRef:
        key: authelia-login
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users-database
  namespace: authelia
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: local-secrets
    kind: SecretStore
  target:
    name: authelia-users-database
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        users_database.yml: |
          users:
            {{ .authelia_username }}:
              displayname: "{{ .authelia_username }}"
              password: "{{ .authelia_password | bcrypt }}"
              email: admin@home.example.com
              groups:
                - admins
  dataFrom:
    - sourceRef:
        storeRef:
          name: local-secrets
          kind: SecretStore
      rewrite:
        - regexp:
            source: '(.*)'
            target: 'authelia_$1'
      extract:
        key: authelia-credentials
