---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: truecharts-oci
  namespace: argocd
stringData:
  url: tccr.io/truecharts
  name: truecharts
  type: helm
  enableOCI: 'true'
