---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freeradius-secret
  namespace: freeradius
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: freeradius-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: freeradius
        property: secret
---
# Generate clients.conf as a ConfigMap via ExternalSecret template
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freeradius-clients
  namespace: freeradius
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: freeradius-clients
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        clients.conf: |
          # UniFi Dream Machine as RADIUS client
          client unifi {
              ipaddr = 10.11.12.1
              proto = udp
              secret = {{ .secret }}
              nas_type = other
              virtual_server = default
          }
          # K3s pod network - requests arrive via CNI
          client k3s-pods {
              ipaddr = 10.42.0.0/16
              proto = udp
              secret = {{ .secret }}
              nas_type = other
              virtual_server = default
          }
  data:
    - secretKey: secret
      remoteRef:
        key: freeradius
        property: secret
