---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword-connect.svc.cluster.local:8080
      vaults:
        homeserver: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-credentials
            namespace: onepassword-connect
            key: token
