---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alexa-shopping-list-config
  namespace: alexa-shopping-list-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
